### ISSUE TITLE
Questions about the train/test split

### ISSUE THREAD

**Issue by deklanw** [Aghasemian/OptimalLinkPrediction#2]
Is this a correct interpretation of how this works:

By randomly removing edges we're simulating creating a 'past' state of the graph. In the paper you do so twice, so we end up with three 'snapshots' of the graph: G_train < G_ho < G_orig

Then, in the training phase we're trying to predict the 'missing' edges E_ho \ E_train with every non-edge of G_ho as negatives, and in the test phase we're trying to predict the 'missing' edges E_orig \ E_ho with every non-edge of G_orig as negatives.

If that's all correct, why is it necessary to create two snapshots? Why can't we just randomly remove edges once to create: G_past < G_orig, positives are E_orig \ E_past and negatives are non-edges of G_orig, and then just do a random 80-20 split for training/test? In other words, why do training and test have to be separate graphs?

And, if we did want to create two snapshots, why does E_train have to be a strict subset of E_ho? Couldn't we have the random edge removal for G_train and G_ho be independent?

Thanks for any help. I'm trying out something similar to your paper, so thanks for this repo and the paper.

**Comment by Aghasemian** [comment]
Thanks for your interest in our paper. I agree that you can design your experiments in a variety of ways. Regarding your first question, you can imagine what we did is an almost 50-50 split. As you understand correctly, we have two states, one observed state that is created by first removal and one training state that is created by second removal. For your second question, we tried to make sure not to have leakage from the training set to the unseen set. Does that make sense?

**Comment by deklanw** [comment]
Thanks for the quick reply.

I'm trying my best to understand the trade-offs with experiment design options. Different papers I'm reading appear to be doing different things.

Yes, the leakage thing makes sense (if I'm understanding correctly, you mean leakage between training and test sets). But, if you sample 20% without replacement twice, independently, won't the overlap be small?

I've been trying out the method in your paper. I remove 20% of the total edges for the testing set, and then another 20% of the total edges for the training set. But, I'm getting a strange situation where it seems like performance on the test graph is higher than my average 5-fold CV performance (AUROC and AP) while tuning (on the train graph).

I thought about it a bit and I realized: when we remove edges aren't we destroying the graph's structure? The test graph has only a bit of structure destroyed, but the training graph has more structure destroyed. So, isn't the edge prediction in the training graph 'harder' than on the test graph?

Instead of sampling twice independently, couldn't we sample 20% of edges, and then sample a disjoint set of 20% of edges? Then, the training graph and test graphs would have roughly equal amounts of 'destroyed structure'.

Would this make sense?

**Comment by Aghasemian** [comment]
No, I didn't have this issue. I even have to control overfitting in my experiments. Would you please explain more about your experiments? What kind of algorithms you are going to stack? Are you using the same networks released in this page?

**Comment by Aghasemian** [comment]
No, I think that's fine too.

**Comment by deklanw** [comment]
Thank you for all the help
